[program:plantgraft]
command= /home/toor/plantgraft/deploy/server.sh
directory=/home/toor/plantgraft/
autostart=true
autorestart=true
stopasgroup=true
user=toor
stdout_logfile = /home/toor/plantgraft/logs/supervisor.log